// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6rnFjoXroADCFwWAMLiOjgK4Fdj_l6WY',
    appId: '1:1005144802323:web:b08af97fe4c51c5fb1abe6',
    messagingSenderId: '1005144802323',
    projectId: 'spot-check-388006',
    authDomain: 'spot-check-388006.firebaseapp.com',
    storageBucket: 'spot-check-388006.appspot.com',
    measurementId: 'G-QZ9QV1JCM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuKKb9ZXATKIkz3pTe4AzySz4MtslbNoc',
    appId: '1:1005144802323:android:6ef3b7c834b9bca5b1abe6',
    messagingSenderId: '1005144802323',
    projectId: 'spot-check-388006',
    storageBucket: 'spot-check-388006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEVr0nLVUn23sfJ9L_0ZF29yV2Gdqa02E',
    appId: '1:1005144802323:ios:cd1dcb1ed1069ec3b1abe6',
    messagingSenderId: '1005144802323',
    projectId: 'spot-check-388006',
    storageBucket: 'spot-check-388006.appspot.com',
    iosBundleId: 'com.example.spotCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEVr0nLVUn23sfJ9L_0ZF29yV2Gdqa02E',
    appId: '1:1005144802323:ios:cd1dcb1ed1069ec3b1abe6',
    messagingSenderId: '1005144802323',
    projectId: 'spot-check-388006',
    storageBucket: 'spot-check-388006.appspot.com',
    iosBundleId: 'com.example.spotCheck',
  );
}
